packages:
  - 'packages/conductor'
  - 'packages/sdk'
  - 'packages/manifest-tools'
  - 'packages/shell'
  - 'packages/plugins/canvas'
  - 'packages/plugins/components'
  - 'packages/plugins/control-panel'
  - 'packages/plugins/header'
  - 'packages/plugins/library'
  - 'packages/contracts'
  - 'packages/tooling'

catalog:
  typescript: '5.3.3'
  vitest: '1.0.4'
  eslint: '8.54.0'
  prettier: '3.1.0'

